[workspace]
members = ["common", "benches", "aoc_*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
regex = "1.11.1"
rayon = "1.10"
# phf = { version = "0.11", features = ["macros"] }
# winnow = "0.6.21"

[profile.bench]
lto = true
