[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
anyhow = { workspace = true }
regex = { workspace = true }
rayon = { workspace = true }

ahash = "0.8"
winnow = "0.6"
tree-ds = { version = "0.1.6", features = ["print_node_id"] }
