[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
itertools = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
rayon = { workspace = true }
kdtree = "0.8.0"
